### PR TITLE
remove intercom, adds new trackers

### PR DESCRIPTION
**Pull request by patjack**

### CODE REVIEW

**Comment by englehardt** [comment]
Thanks @patjack! Let me know when you're ready for review.

**Comment by patjack** [comment]
@englehardt will do!

**Comment by englehardt** [comment]
If possible, would you mind to fix https://github.com/mozilla-services/shavar-prod-lists/issues/62 as part of this PR? Thank you!

**Comment by patjack** [comment]
@englehardt I just added a fix for the entity list that should fix #62. Also feel free to review now. Thanks!

**Pull request merged**
