### PR TITLE
 pulls in latest disconnect blacklist, updates entity list

### PR DESCRIPTION
**Pull request by disconnectme**

### CODE REVIEW

**Comment by groovecoder** [comment]
Thanks @disconnectme and @patjack. Do you know if there will be more updates soon(-ish)? Every update sends approx. 150-200 *terrabytes* of data from Cloudfront to Firefox clients, so we'd like to lump these updates together as much as possible.

**Comment by patjack** [comment]
@groovecoder thanks for the heads up! The next batch of updates should be ready in the next few weeks. If it's better to wait, this PR can be closed and we can lump these and the next changes into a new PR.

**Comment by groovecoder** [comment]
Do you know a more specific timeframe yet? Any major changes in the next update? (e.g., the last update fixed Yandex Maps with Tracking Protection. [Yay!])

**Comment by patjack** [comment]
The next update will include new crypto miners, other trackers, and tags. We are shooting for the first week of December.

**Comment by groovecoder** [comment]
Thanks @patjack. Let's hold this update until we have those other significant updates too.

**Comment by englehardt** [comment]
Fixes #39.

**Comment by englehardt** [comment]
@patjack do you mind to rebase this on the new master? You should be able to add the category tags back in.

**Comment by patjack** [comment]
@englehardt no problem. I just pushed w/the category tags.

**Comment by patjack** [comment]
@groovecoder sounds good!

**Comment by groovecoder** [comment]
If you're not already, please follow https://bugzilla.mozilla.org/show_bug.cgi?id=1515806 for status updates as we go.

**Comment by groovecoder** [comment]
Merging this in. Will watch the output of the next production jenkins job, which should run in about 20m.

**Comment by patjack** [comment]
Hmm... this appears to be a bug.  It's tagged as `cryptominer` so it should only exist in those cryptomining lists and not `base-track-digest256`

**Pull request merged**
