### PR TITLE
Recent Disconnect list additions

### PR DESCRIPTION
**Pull request by patjack**
See individual commits for full details

### CODE REVIEW

**Comment by englehardt** [comment]
@patjack I notice this doesn't contain `google.com` as added here: https://github.com/disconnectme/disconnect-tracking-protection/commit/f2550bc3025babf6b844927e7a3acbe65e5ba3d3#diff-f5fb0346ca2de022483b15e81d888f18R7651. Would you mind to add that in a separate commit from the smartlock changes?

**Comment by patjack** [comment]
@englehardt no problem. I just added the commit here: https://github.com/mozilla-services/shavar-prod-lists/pull/90/commits/4bf95d459d1b401bcbad3d2d0bece75be3bd342c.

**Comment by englehardt** [comment]
These should only be merged into the Nightly list.

**Comment by skim1102** [comment]
Screen Shot 2020-01-03 at 11 39 48 AM
Diff after applying these changes locally.

**Comment by skim1102** [comment]
Screen Shot 2020-01-03 at 11 50 48 AM
Reran locally after merging into `master` branch to confirm none of the versioned branch was affected.

**Pull request merged**
