### PR TITLE
Recent (2024-08#1) Disconnect entity updates or removals, adds`ConsentManagers` category

### PR DESCRIPTION
**Pull request by patjack**
Recent Disconnect list entity updates and removals. Please see individual commits for details. Please let me know if you have any questions. Thanks!

- https://github.com/disconnectme/disconnect-tracking-protection/commit/d3e46468172e2ca81a51be911d9677fa53377588
- https://github.com/disconnectme/disconnect-tracking-protection/commit/baca82757acf7ec84de75ff3283c9ad52c3fc1b7

### CODE REVIEW

**Comment by artines1** [comment]
Hi Patrick,

We noticed that the CMP domain gets moved from the ad tracker list into the new list. Does this means that `cookiebot` is no longer considered as ad tracker? If not, we will expet `cookiebot` exist on both lists, so we can keep blocking it when tracking protection is enabled for now.

**Comment by patjack** [comment]
> We noticed that the CMP domain gets moved from the ad tracker list into the new list. Does this means that `cookiebot` is no longer considered as ad tracker? If not, we will expet `cookiebot` exist on both lists, so we can keep blocking it when tracking protection is enabled for now.

Hi Tim,

We primarily removed `cookiebot` as an advertising tracker due to their [legally binding, public commitment](https://support.cookiebot.com/hc/en-us/articles/14455846346652-Data-processed-when-using-Cookiebot-CMP) not to track users for the purposes of advertising (so their domains no longer fit our definition of the Advertising tracker category):

> The Consent ID is used solely for the purpose described above [consent management] and never for any kind of user tracking by Cookiebot.

And their [DPA](https://www.cookiebot.com/en/wp-content/uploads/sites/7/2024/06/DPA_06_2024.pdf):

> Usercentrics does not collect data regarding a particular end user’s or device’s activity across multiple data controllers. Any data processed and collected as part of the CMP’s processes are only done so in the context of the controller’s websites. Users or devices will not be fingerprinted, tracked or otherwise matched across visits to different controllers, even if those sites all happen to use our CMP solution.

**Comment by artines1** [comment]
Thanks for explaining why `cookieBot` was removed from the ad tracker list. In this case, we expect `cookieBot` to be excluded from the CMP list because this list is used to unblock the loading of blocked CMP under certain conditions. If the domain is not part of any tracking list, we don't need to explicitly put it into the CMP list.

**Comment by artines1** [comment]
Hi @patjack, Could we exclude the `ConsentManagers` category from the commit for now? The commit only contains the change for `cookiebot.com`, which has been removed from the ad tracker category. We expect the `ConsentManagers` category to only contain domains in other tracker categories. So, if the `cookiebot.com` is not longer a tracker, we don't need to add it to the `ContentManagers` category. Thanks.

**Comment by patjack** [comment]
Hi @artines1, Domains in the ConsentManager category are still considered trackers but these domains will not appear in other tracker categories based on the required commitment to be placed in the ConsentManager tracker category, which requires that domains commit to only track for purposes of consent management and not advertising, analytics, etc. We could exclude the ConsentManagers category for the commit for now, please confirm.

**Comment by artines1** [comment]
Hi @patjack,

Since ConsentManagers are considered trackers, we want to block them and keep the information regarding their original tracking category. In this case, we expect to put the ConsentManager domains in both the ConsentManager category and their original tracker categories. This would be the easiest way for us to keep blocking them and maintaining the information.

Please revert the following lines to keep the `cookiebot.com` in the ad tracker category. Really appreciated.
```
-      {
-        "UserCentrics": {
-          "https://www.usercentrics.com": [
-            "cookiebot.com"
-          ]
-        }
-      },
```

**Comment by patjack** [comment]
@artines1 no problem! Please see the latest changes.

**Review by artines1 — APPROVED** [review]

**Pull request merged**
