### PR TITLE
Recent (2021-04#1) Disconnect List additions

### PR DESCRIPTION
**Pull request by patjack**
This PR contains recent Disconnect list additions. 

See: https://github.com/disconnectme/disconnect-tracking-protection/commit/0392c293b2fde3d79baa2f19ff13dac37d151fd2

See: https://github.com/disconnectme/disconnect-tracking-protection/commit/81ec354c32f46cabbbe37517393903ed9851bc61

### CODE REVIEW

**Review by say-yawn — CHANGES_REQUESTED** [review]
@patjack it seems AppCast is still in invasive fingerprinting list see [these lines](https://github.com/mozilla-services/shavar-prod-lists/pull/477/files#diff-b2429c478afd73256cde0800a548ad83227a9a42ea36d0d72f655f56cfd9cebbR10501-R10506). I believe https://github.com/mozilla-services/shavar-prod-lists/pull/476/commits/476e04f519596b1ad6ab39c33a33dcbfdc3934f2 moved AppCast from invasive to general category. Can you confirm and correct this? Thanks!

**Comment by patjack** [comment]
> @patjack it seems AppCast is still in invasive fingerprinting list see [these lines](https://github.com/mozilla-services/shavar-prod-lists/pull/477/files#diff-b2429c478afd73256cde0800a548ad83227a9a42ea36d0d72f655f56cfd9cebbR10501-R10506). I believe [476e04f](https://github.com/mozilla-services/shavar-prod-lists/commit/476e04f519596b1ad6ab39c33a33dcbfdc3934f2) moved AppCast from invasive to general category. Can you confirm and correct this? Thanks!

@say-yawn you're right! I just pushed a new commit that fixes this.

**Review by say-yawn — APPROVED** [review]
LGTM

**Review by say-yawn — APPROVED** [review]

**Comment by say-yawn** [comment]
@patjack it seems the force-push was unable to deal with the merge conflict. Can you rebase to latest main please?

**Comment by patjack** [comment]
@say-yawn I pulled w/rebase on the main and pushed the changes to this branch. It looks like it auto-closed because its up to date now.

**Comment by say-yawn** [comment]
https://github.com/mozilla-services/shavar-prod-lists/commits/master Yeah. It looks like it got merged according to f93025c63fbc56f680a9408d25a5a16607b35ed2? Seems like some sort of GitHub bug.

**Pull request closed without merging**
