### PR TITLE
Recent (2020-10#1) Disconnect list entity updates or removals

### PR DESCRIPTION
**Pull request by patjack**

### CODE REVIEW

**Review by englehardt — APPROVED** [review]

**Comment by englehardt** [comment]
@patjack was there a commit related to `avantmetrics.com` that you forgot to include in the commit message?

**Comment by patjack** [comment]
@englehardt I think that was added by @kasnder with this commit: https://github.com/mozilla-services/shavar-prod-lists/commit/c400436d20bd23bf688ec47e972be2726fa5a761. I removed it because it's not a change that's currently on our list.

**Comment by say-yawn** [comment]
@englehardt, @patjack it seems it was erroneously added to the Advertising category. It should only show up on the FingerprintingGeneral category. It seems the script comparing the two was grouping all the entities across the category rather than comparing between the categories.

**Comment by say-yawn** [comment]
@englehardt this change is going into all version of lists.

**Comment by englehardt** [comment]
> @englehardt this change is going into all version of lists.

SGTM

**Comment by say-yawn** [comment]
So it seems that when Fingerprinting category was updated to FingperprintingInvasive and General (we only use Invasive on the list script) we did not add the General category and let it ride the version trains https://github.com/mozilla-services/shavar-prod-lists/pull/284. As such, the first two commits `13c0a6a1a93e7dd9cbc8d60fa8c6d43d5abc5d06` and `52f969a754c7e607ff471422ccf79f8a7dc7315b` will be just removing the domains from the invasive category only  https://github.com/mozilla-services/shavar-prod-lists/pull/368/commits

**Pull request merged**
