### PR TITLE
Recent Disconnect list entity updates or removals (2020-08-1)

### PR DESCRIPTION
**Pull request by patjack**
See: https://github.com/disconnectme/disconnect-tracking-protection/commit/65f3f14945dd43c92952569fee1185d301e2a20e
https://github.com/disconnectme/disconnect-tracking-protection/commit/f8d693f720804896cece18a3f0a83ee969f15879

### CODE REVIEW

**Comment by hkolk** [comment]
@say-yawn @englehardt (sorry for tagging you if that is very rude...)
Hey Mozilla people! Currently this is causing quite an issue on multiple sites in the eBay Classifieds Group network that is utilizing eBay's Image service and was found to be blocked as of firefox 78. The above commits will add the websites that are using the image service for whitelisting.

Without this, any user with stricter checking is unable to see any (user-uploaded) images of classifieds on our website. You can verify this issue by going to https://www.marktplaats.nl/ and see missing images on the homepage. Disabling the tracking protection shows the images.

Would it be possible to fast-track this request? We have spend some time diving into the shavar service and logic and we guess that would be the proper fix.

At the moment the only advise we can give to our users is to disable the protection, which is what I guess both mozilla and the user's don't want. 

If you have any questions or concerns about this change, or how this domain is used, you can contact me through github or hkolk@<4-letter-name-company>.com. 

Thanks in Advance!
- Harm

**Comment by cluehr** [comment]
@patjack, is there a way to speed this up a bit? As @hkolk pointed out, it is really important to get this into production as quick as possible.

**Comment by englehardt** [comment]
@hkolk @cluehr We will deploy this today. Thanks for helping us get this fixed.

**Comment by say-yawn** [comment]
The changes in this PR has been merged to all supported versions of Firefox. I tried to reproduce the issue @hkolk pointed out on Nightly (81.0a1) and confirmed it was broken and when I applied with the fix (getting the latest Shavar prod list changes to the client) I confirmed that `ebayimg.com` is no longer blocked on `marktplaats.nl` and the images show up. 
## Before applying the fix:
nightly-marktplaats

## After applying the fix:
nightly-fixed

The Shavar updates should be rolling out to Release and other clients now. Thanks for helping out @hkolk @cluehr.

**Comment by cluehr** [comment]
Thank you, @say-yawn for merging this PR! Much appreciated!

**Comment by cluehr** [comment]
@say-yawn , do you know how long it takes until my locally installed Firefox picks this new configuration?

**Comment by say-yawn** [comment]
Just confirmed that it went out live.

**Pull request merged**
