### PR TITLE
removes the "tag" counts in json_verify.py

### LINKED ISSUE #120: Add more checks in Travis CI
# About this Issue
To make the PR tests be more robust and comprehensive we should add additional checks/tests in Travis CI to check for the following:

# Acceptance Criteria
- [ ] Check the diff between shavar-prod-lists and disconnect-tracking-protection and have Travis CI fail if it ever finds domains in our list that aren't in Disconnect's
- [ ] Check the list files updated (run shavar-list-creation) from the changes in the shavar-prod-lists
- [ ] Check that the size of the files updated does not exceed the max file size (3 MB).
- [x] Remove the "tag" counts in the json_verify.py test as it is an outdated format

### PR DESCRIPTION
**Pull request by dave-light**
This PR is still in progress and will resolve #120

### CODE REVIEW

**Comment by dave-light** [comment]
@skim1102 The Travis build is failing, I take it it's because the tags on line 14 to 23 needed to stay? If so I'll add them back.

**Comment by dave-light** [comment]
> @skim1102 The Travis build is failing, I take it it's because the tags on line 14 to 23 needed to stay? If so I'll add them back.

I'm referring to these tags:
FINGERPRINTING_TAG = 'fingerprinting'
CRYPTOMINING_TAG = 'cryptominer'
SESSION_REPLAY_TAG = 'session-replay'
PERFORMANCE_TAG = 'performance'
ALL_TAGS = [
    FINGERPRINTING_TAG,
    CRYPTOMINING_TAG,
    SESSION_REPLAY_TAG,
    PERFORMANCE_TAG
]

**Comment by dave-light** [comment]
Travis is giving assertion errors on lines 56, 151 and 269. 

Also, the commit history is a bit messy because my branch was behind master so I did a git rebase (will avoid doing that in future).

**Comment by skim1102** [comment]
@dave-light can you get the latest from the shavar-prod-lists and use cherry-pick to get just your commits? It seems that this PR is including commits from other changes.

**Comment by skim1102** [comment]
To answer your question about removing the `ALL_TAGS` and the respective tags variables, the issue requests only the tag count to be removed so those variables can stay.
As you noted, removing all those variables and its references resulted into the error:
```
---Error: Recieved error <type 'exceptions.AssertionError'> while parsing file.
Traceback (most recent call last):
  File "scripts/json_verify.py", line 56, in verify
    find_uris(json_obj["categories"])
  File "scripts/json_verify.py", line 151, in find_uris
    assert type(uris) is ListType
AssertionError
```
in https://travis-ci.org/github/mozilla-services/shavar-prod-lists/builds/660856920#L190 because some of the companies in the `disconnect_blacklist.json` still has subcategory tags. You can check for this by putting a debugger after `if tag_value == "":` on this [line](https://github.com/mozilla-services/shavar-prod-lists/pull/143/files#diff-dcfa8ff35c28748de06e2f41cc4c2beaR148).

**Pull request closed without merging**
