### PR TITLE
89.0 - Update Blacklist.

### PR DESCRIPTION
**Pull request by martvtex**
Hello,

We at VTEX were recently on the invasive fingerprint list of disconnectme, but we have been removed from this list in this commit by disconnectme.

https://github.com/disconnectme/disconnect-tracking-protection/commit/e820689af2ff6c1109ac3307959f70ef8704df57

Reading [1] this link, I didn't find a deploys roadmap to know when the new version with the updated list will be deployed.

[1] https://wiki.mozilla.org/Security/Tracking_protection#Lists

Could it be updated?

Thank you very much in advance,

### CODE REVIEW

**Comment by martvtex** [comment]
@say-yawn can you help me here?

Thanks in advance. I was thinking in open an issue but the pr seemed more right (correct if I was wrong).

**Comment by say-yawn** [comment]
Hi @martvtex! Thanks for submitting this PR. Issue would have been preferred but this works as well. Normally I wait for Disconnect to send me their changes as not all of their changes always get adopted for our use. @patjack were you going to create a PR with the changes mentioned above?

**Comment by patjack** [comment]
@say-yawn definitely! I'll create a PR with these changes shortly.

**Comment by martvtex** [comment]
Hey @say-yawn and @patjack , thanks a lot.

We did talk with disconnectme 26 days a go, its something that we can help with this kind of situation? Or there is any roadmap that I was not aware?

Thanks again <3

**Comment by say-yawn** [comment]
Closed in favor of #526

**Pull request closed without merging**
