### PR TITLE
bug 1432650: wip: fail verify on dupe upper domain

### PR DESCRIPTION
**Pull request by groovecoder**
Example output running this:
```
shavar-prod-lists lcrouch$ ./scripts/json_verify.py

disconnect-blacklist.json : invalid
	Dupe: Dupe host: api-maps.yandex.ru	 in line 7509

disconnect-entitylist.json : valid

google_mapping.json : invalid
	Dupe: Dupe host: api-maps.yandex.ru	 in line 0

 block_host_uris: 2347

 entity_host_uris: 3870
```

TODO:
* [ ] Debug why the same dupe error is thrown for `google_mapping.json` file

### CODE REVIEW

**Comment by ulis-grand** [comment]
You are already seeing who are the ones who are making false stories. And everything blamed on mee.

**Comment by ulis-grand** [comment]
They tritp me. Say the Jason aplication is but. And they put disconnect 
[github-recovery-codes.txt](https://github.com/mozilla-services/shavar-prod-lists/files/2177257/github-recovery-codes.txt)

**Comment by groovecoder** [comment]
Removed review request.

**Comment by sarah1191** [comment]
H

**Review by Adams214565 — APPROVED** [review]

**Comment by Trikolon** [comment]
@groovecoder this looks stale, should we still do it or should we close the PR?

**Pull request closed without merging**
