### PR TITLE
Add dnt:eff to itisatracker.com

### PR DESCRIPTION
**Pull request by carbureted**

### CODE REVIEW

**Comment by fmarier** [comment]
Thanks @carbureted !

Javaun, we should NOT merge this until we get the go ahead from Cloud Services that the list creation script is ready to handle it.

**Comment by fmarier** [comment]
I believe this is ready to be merged once it's been rebased.

**Comment by javaun** [comment]
Fmarier, does this need to wait for a 49 to go live? Do we alter existing lists, or does the new list script parsing only affect newly created lists?

**Comment by fmarier** [comment]
> Does this need to wait for a 49 to go live? Do we alter existing lists, or does the new list script parsing only affect newly created lists? 

We don't have to wait, our list creation script now generates both sets of lists: the old ones for Firefox 42-49, and the new ones for Firefox 50+.

**Comment by groovecoder** [comment]
Superseded by https://github.com/mozilla-services/shavar-prod-lists/pull/18 which includes rebased commit for merge.

**Pull request closed without merging**
