### PR TITLE
Fixes duplicate domains, adds new trackers, updates corp/domain association

### PR DESCRIPTION
**Pull request by patjack**
This PR addresses issues with #56 (duplicate domains, augur back as tracker), some new trackers, and updates several corp/domain associations

### CODE REVIEW

**Comment by patjack** [comment]
Hi @englehardt - just a heads up that I'm done w/changes for this PR. This includes all the latest changes from the [Disconnect list](https://github.com/disconnectme/disconnect-tracking-protection/commits/master). Let me know if you have any questions. Thanks!

**Comment by englehardt** [comment]
@patjack does this complete the 2019-03-04 report?

**Comment by patjack** [comment]
@englehardt Yes, that is correct. There are a few that require a more in depth review but not many.

**Comment by patjack** [comment]
@englehardt I pushed [more fingerprinters](https://github.com/disconnectme/disconnect-tracking-protection/commit/753af089765ffa33e2fe21b23d8a1b8a281ef6bd) on the disconnect repo. Should I add the changes here or wait until the next PR?

**Comment by englehardt** [comment]
I haven't started reviewing them yet, so please add them here. Thank you!

**Pull request merged**
