### PR TITLE
Move Amazon international domains to content

### PR DESCRIPTION
**Pull request by mkaply**
Test to see if this fixes the Amazon extension,

### CODE REVIEW

**Comment by groovecoder** [comment]
Hi @mkaply. We should get @disconnectme and @patjack to verify this is okay.

**Comment by mkaply** [comment]
disconnect is not OK with this. The reason I put together this pull is because I want to stage the fix to at least see if it fixes the problem and then back it out.

**Comment by groovecoder** [comment]
Can you use https://github.com/mozilla-services/shavar-test-lists for that?

**Comment by mkaply** [comment]
I didn't even know that was a thing. I'll move it over there.

**Pull request closed without merging**
