### PR TITLE
More specific Yandex service blocking

### PR DESCRIPTION
**Pull request by carbureted**
Blocking all of Yandex is probably too broad and may cause a bad UX on some sites.

### CODE REVIEW

**Comment by fmarier** [comment]
Maybe we should update the entitylist in the same PR?

**Comment by javaun** [comment]
Yeah,  let's assess the breakage if we don't update the whitelist . The
entity list is the expensive one,  we may also decide to hold both changes
until we have a larger update

**Comment by carbureted** [comment]
Hrm, I might be confused as to exactly how the entitylist is used by Firefox. (Or maybe misinterpreted your comments! Let me know if I'm totally off base.)

If the entitylist works the way I assume that it does (please correct me if not, I might be drawing the wrong assumptions from the way Disconnect's blocking engine works), then we shouldn't need to update it in order to limit the blocking to specific tracking services. We still want metrika.yandex.ru (and other third-party tracking subdomains) to continue to work on yandex.by and other yandex-owned sites, so we need to keep all of yandex's top-level domains on the entitylist the same way they are now so that metrika.yandex.ru isn't blocked on yandex.ru.

I should put the broader yandex domains into the content category as well, though.

**Comment by fmarier** [comment]
> We still want metrika.yandex.ru (and other third-party tracking subdomains) to continue to work on yandex.by and other yandex-owned sites, so we need to keep all of yandex's top-level domains on the entitylist the same way they are now so that metrika.yandex.ru isn't blocked on yandex.ru.

You're right when it comes to the [properties section](https://github.com/mozilla-services/shavar-prod-lists/blob/f4aa331791db37089be0ad6aeaa7727443054300/disconnect-entitylist.json#L7215-L7224). That section should stay the same since the Yandex web properties haven't changed.

On the other hand the [resources section](https://github.com/mozilla-services/shavar-prod-lists/blob/f4aa331791db37089be0ad6aeaa7727443054300/disconnect-entitylist.json#L7225-L7234) should be updated since the blacklist no longer blocks anything on these domains:

- `web-visor.com`
- `moikrug.ru`
- `yandex.st`

It wouldn't break anything to leave them on there, but we should work towards reducing list bloat as we take things out of the list. Otherwise, we'll end up generating, for each domain in the `properties` section, these whitelisted pseudo-URLs:

- `yandex.com/?resource=web-visor.com`
- `yandex.com/?resource=moikrug.ru`
- `yandex.com/?resource=yandex.st`

**Pull request merged**
