### PR TITLE
adds new top-level category, Fingerprinting. removes previous tags

### PR DESCRIPTION
**Pull request by patjack**
This is similar to the last PR. Fingerprinters are no longer identified using tags and are broken out in their own top-level category: `Fingerprinting`

### CODE REVIEW

**Comment by englehardt** [comment]
Thanks Patrick! I'll need to update our list consumption scripts before we can merge this.

I notice that this change moves a lot of fingerprinting domains out of the Analytics/Advertising categories. Have these domains been reviewed as trackers as well? That is, can I assume that all of the domains that have been removed from the Analytics category and added to the Fingerprinting category were reviewed both as potential trackers and potential fingerprinters, and found to not meet the definition of tracking but to meet the definition of fingerprinting? Or is it the case that some of these simply haven't yet been reviewed as trackers?

**Comment by patjack** [comment]
Hi Steven, no problem! The majority of the fingerprinting tagged domains were kept in Advertising or moved to Analytics. Only a few are moved out of Advertising/Analytics and only exist in Fingerprinting. Of the entries that only exist in Fingerprinting, they may eventually be added to Advertising/Analytics after more policy review or stay solely in fingerprinting because they only meet the definition of fingerprinting.

**Comment by patjack** [comment]
Just a heads up that I have a few more commits coming this week and I'll add a comment when I'm done.

**Comment by englehardt** [comment]
Thanks for the heads up! We are planning to review this next week, so that should be perfect.

**Comment by patjack** [comment]
I'm done with the changes for this PR. Please let me know if I can help w/anything. Thanks!

**Comment by englehardt** [comment]
@patjack does this complete the review of the `2019-02-16` domain report?

**Comment by patjack** [comment]
@englehardt that is correct. I have about ~20 observations that need more analysis but I can add those in on next update.

**Comment by patjack** [comment]
@englehardt thanks for flagging Augur. This was unintentional when the new category was made and it shouldn't have been removed as a tracker. I'll fix this and the duplicate domain issue.

**Comment by englehardt** [comment]
@patjack thanks!

**Comment by englehardt** [comment]
@patjack do you expect to keep https://github.com/disconnectme/tracker-descriptions in sync with these list updates?

**Comment by patjack** [comment]
@englehardt yeah we do. That repo is lagged behind at the moment but we are working on updating it w/latest changes.

**Comment by englehardt** [comment]
@patjack we're gong to merge this now, mind to add the fixes for https://github.com/mozilla-services/shavar-prod-lists/pull/56#pullrequestreview-213102271 in a new PR?

**Comment by patjack** [comment]
@englehardt, sounds good. I have that and some other changes that I'll add in a new PR

**Pull request merged**
